# Generated by Django 4.2 on 2023-04-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bread',
            new_name='Breed',
        ),
    ]
